In [2]:
def test():
    return
test()

In [6]:
class Demo:
    def test(self):
        print("test() for the class and method")
        return
obj=Demo()
obj.test()

test() for the class and method


In [10]:
def fact(n):
    fact=1
    while(n!=0):
        fact=fact*n
        n=n-1
    return fact
fact(5)

120

In [14]:
class Demo1:
    def fact(self,n):
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=Demo1()
p1.fact(5)

120

In [16]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
        
    def add(self,p1,p2):
        return p1+p2

c1=Demo2(10,20)
print(c1.add(10,20))

30


In [21]:
class person():
    def __init__(self,name):
        self.name=name
    def getName(self):
        return self.name
    def isEmployee(self):
        return False
class Employee(person):
    def isEmployee(self):
        return True
emp=person("Anil")
print(emp.getName(),emp.isEmployee())
emp1=Employee("Akhil")
print(emp1.getName(),emp1.isEmployee())

Anil False
Akhil True


In [23]:
lst=[1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [25]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [28]:
lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)
print(array)

(4,)
int64
[1 2 3 4]


In [30]:
lst=[1.2,5.3,7.5,8.5]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
float64


In [34]:
#Re shape
#numpy.reshape
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)
#a1.reshape(6,1)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
#append some data
#vstack(array1,array2)
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [39]:
#generate random numbers from np
a1=np.random.normal(5,0,10)
print(a1)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [41]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]])

In [43]:
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [47]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [49]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]
